[package]
name = "rust-snippets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
serde_json = "1.0"
#tracing = "0.1"
#tracing-subscriber = { version = "0.3", features = ["env-filter"] }

#tokio = { version = "1.42", features = ["full"] }
