[package]
name = "rust-demo-app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

chrono = "0.4.39"

axum = "0.7.9"

