[package]
name = "rust-demo-commons"
version = "0.1.0"
edition = "2021"
description = "common code."


[dependencies]
anyhow.workspace = true

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
