name: Docker

on:
  workflow_run:
    workflows: [Build]
    types: [requested]
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
#    - name: setup docker buildx
#      uses: docker/setup-buildx-action@v2

    - name: docker login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ vars.DOCKERHUB_USERNAME_XX }}
        password: ${{ secrets.DOCKERHUB_TOKEN_XX }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: my-docker-hub-namespace/my-docker-hub-repository

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
