name: Docker

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    runs-on: ubuntu-latest
#    permissions:
#      packages: write
#      contents: read
#      attestations: write
#      id-token: write

    steps:
#    - uses: actions/checkout@v4
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: bdom/rust-demo-service-temp

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
#        context: .
#        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
